- hosts: all
  become: 'yes'
  tasks:
    - name: Install required system package
      apt:
        pkg:
        - docker.io
        update_cache: true
        cache_valid_time: 60
    - name : Docker custom setup 
      shell: |
        useradd -s /bin/bash -p $(openssl passwd -1 spoonable) spoonable
        echo 'spoonable ALL = (root) NOPASSWD: /bin/nano' >> /etc/sudoers.d/spoonable